using UnityEngine;
using System;
using System.Collections.Generic;

// *** Class Generated By SaveDataEditor ***
namespace CarterGames.Assets.SaveManager
{
    [Serializable]
    public class SaveData
    {
        public int highestLevelUnlocked;
        public int lastLevel;
        public LevelData[] levelData;
    }

    
    [Serializable]
    public class LevelData
    {
        public bool isUnlocked;
        public bool isCompleted;
        public short stars;
    }
}